name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '9.0.x' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          
      - name: Display dotnet version
        run: dotnet --version

      - name: dotnet restore
        run: dotnet restore
      
      - name: dotnet build
        run: dotnet build
